### PR TITLE
Update fibs and fibs_spec - Ramkumar Ramanathan

### PR DESCRIPTION
**Pull request by ramkumar1987**
Hi ,

I was asked to complete the following project as part of the interview process for the position of Software engineer in Vertical response. 

I have implemented the Fibs class as per the specs in the fibs_spec.rb spec file as per the the first phase of the project mentioned in the corresponding README.md file.

I was not able to push my changes directly to the main repo url : https://github.com/VerticalResponse/eng_basics

Do you need to add me as a collaborator ?

So i forked the project and pushed my changes to a branch (ram_fibo) on this forked project

Please review the pull request and let me know your suggestions.

Thank you,
Ramkumar

### CODE REVIEW

**Comment by josephrider** [comment]
@ramkumar1987 
Thank you for taking the time to complete the first part in the series.  Good work.

Completing the second part (https://github.com/VerticalResponse/eng_basics#rails-basics) is optional, but not discouraged.  Please review the third section (https://github.com/VerticalResponse/eng_basics#js-basics), complete the coding goals to the best of your ability and add a commit to this PR when you're ready.

Cheers!

**Comment by ramkumar1987** [comment]
Hi,

I will start working on the other sections soon. Thank you for getting back.

Thank you,
Ram

**Comment by ramkumar1987** [comment]
@josephrider  ,

Hi,

I am a little new to javascripts and asyncronous request responses. I am making full effort to learn in depth the same, rather than just hacking a solution without gaining through understanding of what i am doing. Plus i am juggling my office projects with the project quiz. 

Please give some time and i should have it up and running by the end of next week.

Thank you,
Ram

**Comment by josephrider** [comment]
We'll review this offline.  Thanks for spending the time.  Closing this PR.

**Pull request closed without merging**
